flux:
  interval: 2m
  rollback:
    cleanupOnFail: false

networkPolicies:
  enabled: false

kiali:
  enabled: false

istio:
  sourceType: helmRepo
  enabled: true

istioOperator:
  sourceType: helmRepo
  enabled: true

monitoring:
  sourceType: helmRepo
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

loki:
  sourceType: helmRepo
  enabled: true
  strategy: scalable
  values:
    minio:
      enabled: true
    write:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    read:
      replicas: 1
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
    extraobjects:
    - apiVersion: "security.istio.io/v1beta1"
      kind: PeerAuthentication
      metadata:
        name: loki-minio-endpoint-exception
        namespace: logging
      spec:
        mtls:
          mode: STRICT
        selector: 
          matchLabels:
            app: minio
        portLevelMtls:
          "9000":
            mode: PERMISSIVE
promtail:
  sourceType: helmRepo
  enabled: true

kyverno:
  sourceType: helmRepo
  enabled: true

kyvernoPolicies:
  sourceType: helmRepo
  enabled: true
  values:
    policies:
      restrict-volume-types:
        validationFailureAction: Audit
      restrict-image-registries:
        validationFailureAction: Audit
      restrict-host-path-write:
        validationFailureAction: Audit
      restrict-host-path-mount:
        validationFailureAction: Audit
      require-non-root-user:
        validationFailureAction: Audit
      require-non-root-group:
        validationFailureAction: Audit
      disallow-privileged-containers:
        validationFailureAction: Audit
      require-drop-all-capabilities:
        validationFailureAction: Audit
      restrict-host-path-mount-pv:
        validationFailureAction: Audit

neuvector:
  sourceType: helmRepo
  enabled: false
  values:
    k3s:
      enabled: true

sso:
  client_id: il2_eb21db65-3118-4017-bfe7-86829038d3dc_apps
  client_secret: "123456789"
  name: SSO
  url: https://login.gw.local/auth/realms/gamewarden
  # certificateAuthority:
  #   cert: |
  #
  #     -----BEGIN CERTIFICATE-----#     
  #     MIIE5TCCAs2gAwIBAgIBAjANBgkqhkiG9w0BAQsFADAXMRUwEwYDVQQDEwxMb2Nh#     
  #     bCBEZXYgQ0EwHhcNMjQxMTA3MTkxNjAzWhcNMjYxMTA3MTkxNjAzWjAVMRMwEQYD#     
  #     VQQDDAoqLmd3LmxvY2FsMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA#     
  #     lt/BJrKLBfFVyaY34UqGyvuRRaHs0ZzXE0a2hsd3WGQDhMqM0lHh+bUnEVXSv6Gy#     
  #     ItlsDzA/4/Y75CS8LpZd2qP8R0P6nJzo99+zQxIzbIvI+rcUglGQ7914skgt5Hnm#     
  #     0hheLMzQLy4lx73/S+gMSlassBrQ4iRPqDuN28a2aouXrQ3xQUYto/r5JFTRZq0F#     
  #     NqKCOJpd47gbWXpY295NWoWk9pOVGoWshvggQN9yI8Zm30xmYVdWBKSJcrUvXaOH#     
  #     0ALRjg9S/Yayn4C6trXqeIEf/SbBecGV/Dzq3xL5PUK4YqYwxNxR9obzzE6gUU/g#     
  #     HmG0Oi6p54pBqP1kXTJt5s7LrGc6H7IStm1ntIHbrVDZV0Clas9UGzeOAX8iO/JG#     
  #     FLwpzcnaFxKxI0UBEXq4/KDpEbP532kaie6z0c2fTmDIxpQsq3RKkTlTGYSTlmJB#     
  #     Ecekq9hbVjm/8FRLBaK+8CcH6qk5gcaTJ5K3Hr7JnTYF7X8MwolhGkKQpPEny7I5#     
  #     cuB5QKXWYNBuhV66Ne+SYGh0WFbENl258G41EqN8ABdkLOTTpxS53uWWfxOhytsG#     
  #     ab6A1KiRmWeYto67Tccp3koKWo26kAyo7OHEVg/0NbU5eP8bTBgTVFvrvSfoHC1+#     
  #     aqk6qiT2iXzQvxjZl22YmgJfWo4SyuiDNNUpAgq7sOkCAwEAAaM+MDwwDgYDVR0P#     
  #     AQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBUGA1UdEQQOMAyCCiouZ3cu#     
  #     bG9jYWwwDQYJKoZIhvcNAQELBQADggIBAL3dYG5r0iREaP34537/D/gPf7qRhgFS#     
  #     7YiOslshisM6kC1XG/NWxCWHPV5ZLvj+U2U/usrzmsFkFM6ZkQG92mCDP7L+988i#     
  #     vp68VtrA3mPVFLW/H7hZUcsvc9lpc+PaAq82UOQPSWH9rsWzgR7F8jym+aXi3Zy9#     
  #     Yc/v2cbeL965nvxjz0m0LqDBW++A7uHNdO5jknR1wVbI7SnGet1u0hK4xOcakMaw#     
  #     NJT61VQ+RwQ431rantpnOg8gwCbxJcveoyRDtvvJdp63tgvEdxrnvVg5NWTbJl2l#     
  #     KEAO0V5Xq9Qc8EAxWnpwdZdTlsH+3SRNS/5FibrDpUBe7SHu8RQkdJeXrRS/+Ss9#     
  #     cl6FDdh1uFsyPrS9W8s2u8lq2IocVP/GzQBdLozJroicsrH4VhzScP3sezluo58y#     
  #     weWAk3LXr2kpXQy7DI184X5g3RqS+IF2oyMjmQ1DjJ8yMTDrRbV2goGeO3pIjqZn#     
  #     CJqP3VNa6rstdVK+o5yhJ8gE/xv+ew1WnNKCw78DTgQYqpnsormaKwrzySNuCwx6#     
  #     pVDbRp4tOBbThBkWtRDUemhkEljlNAFd+ypTgQie3tVMX8P2A/K9HcoeQ3q8QktV#     
  #     quHes8wFKc/2Sz2ljm0EjDWnYm+KPqIIo+3QIMAyxueBkmaanebKQs64eyO+iNve#     
  #     ylaBxF6Fjlwo#     
  #     -----END CERTIFICATE-----#     

grafana:
  values:
    grafana.ini:
      auth.generic_oauth:
        api_url: "https://login.gw.local/auth/realms/gamewarden/protocol/openid-connect/userinfo"
        auth_url: "https://login.gw.local/auth/realms/gamewarden/protocol/openid-connect/auth"
        client_id: "il2_eb21db65-3118-4017-bfe7-86829038d3dc_apps" #gitleaks:allow
        client_secret: "123456789"
        enabled: true
        groups_attribute_path: "groups"
        name: "Game Warden SSO"
        role_attribute_path: "contains(groups[*], '/Gamewarden/grafana-server-admin') && 'GrafanaAdmin' || contains(groups[*], '/Gamewarden/grafana-admin') && 'Admin' || 'Viewer'"
        role_attribute_strict: true
        scopes: "openid profile email grafana"
        token_url: "https://login.gw.local/auth/realms/gamewarden/protocol/openid-connect/token"


addons:
  authservice:
    enabled: true
    chains:
      APP:
        callback_uri: https://APP.gw.local
        client_id: il2_eb21db65-3118-4017-bfe7-86829038d3dc_apps
        client_secret: "123456789"
        match:
          prefix: "APP.gw.local"
  argocd:
    enabled: true
    sso:
      client_id: "il2_eb21db65-3118-4017-bfe7-86829038d3dc_apps" #gitleaks:allow
      client_secret: "123456789"
      enabled: true
    values:
      server:
        extraArgs:
        - --insecure
        - --repo-server-plaintext
      repoServer:
        extraArgs:
        - --disable-tls
      controller:
        extraArgs:
        - --repo-server-plaintext
      redis-bb:
        networkPolicy:
          enabled: false
      argocd-apps:
        applications:
          - destination:
              namespace: APP
              server: https://kubernetes.default.svc
            ignoreDifferences:
              - jsonPointers:
                  - /data
                  - /stringData
                kind: Secret
                name: generated-secrets
                namespace: APP
            info:
              - name: url
                value: https://github.com/second-front/uchart
            name: APP-ENV
            namespace: argocd
            project: default
            sources:
              - helm:
                  valueFiles:
                    - $values/app/base.yaml
                    - $values/app/ENV.yaml
                path: ./
                repoURL: https://github.com/second-front/uchart.git
                targetRevision: 1.0.10
              - ref: values
                repoURL: https://github.com/sjb720/gwctl-gitops-test-blank-on-git
                targetRevision: main
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              managedNamespaceMetadata:
                labels:
                  istio-injection: enabled
              syncOptions:
                - CreateNamespace=true
                - Validate=false
                - RespectIgnoreDifferences=true
  keycloak:
    enabled: true
    postRenderers:
      - kustomize:
          patchesStrategicMerge:
            - apiVersion: v1
              kind: Service
              metadata:
                name: keycloak-headless
                namespace: keycloak
              spec:
                ports:
                  - name: tcp
                    port: 7800
                    protocol: TCP
                    targetPort: tcp
                  - name: tcp-fd
                    port: 57800
                    protocol: TCP
                    targetPort: tcp-fd
      - kustomize:
          patchesStrategicMerge:
            - apiVersion: networking.istio.io/v1
              kind: VirtualService
              metadata:
                name: keycloak
                namespace: keycloak
              spec:
                tls: null
    values:
      replicas: 1
      args:
        - "start-dev"
        - --import-realm
      extraEnv: |-
        - name: KC_HTTPS_CLIENT_AUTH
          value: request
        - name: KC_HOSTNAME
          value: login.gw.local
        - name: KC_LOG_LEVEL
          value: "org.keycloak.events:DEBUG,org.infinispan:INFO,org.jgroups:INFO"
        - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_SPI_X509CERT_LOOKUP_PROVIDER
          value: nginx
        - name: KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT
          value: istio-mtls-client-certificate
        - name: KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT_CHAIN_PREFIX
          value: UNUSED
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: QUANTUM_EMITTER_NATS_SERVER
          value: nats
      extraInitContainers: |-
        - name: plugin
          image: registry1.dso.mil/ironbank/big-bang/p1-keycloak-plugin:3.5.7
          command:
          - sh
          - -c
          - |
            cp /app/p1-keycloak-plugin.jar /init
            ls -l /init
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
          - name: plugin
            mountPath: "/init"
      extraPorts:
        - containerPort: 7800
          name: tcp
          protocol: TCP
        - containerPort: 57800
          name: tcp-fd
          protocol: TCP
      extraVolumeMounts: |-
        - name: plugin
          mountPath: /opt/keycloak/providers/p1-keycloak-plugin.jar
          subPath: p1-keycloak-plugin.jar
        - name: quarkusproperties
          mountPath: /opt/keycloak/conf/quarkus.properties
          subPath: quarkus.properties
        - name: realm
          mountPath: /opt/keycloak/data/import/realm.json
          subPath: realm.json
          readOnly: true
      extraVolumes: |-
        - name: plugin
          emptyDir: {}
        - name: quarkusproperties
          secret:
            secretName: keycloak-quarkusproperties
            defaultMode: 0777
        - name: realm
          configMap:
            name: gamewarden-realm
      hostname: gw.local
      istio:
        enabled: true
        keycloak:
          gateways:
            - istio-system/public
          hosts:
            - login.gw.local
      proxy:
        mode: xforwarded
      secrets:
        env:
          stringData:
            JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
        quarkusproperties:
          stringData:
            quarkus.properties: |-
              quarkus.http.non-application-root-path=/
              quarkus.kc-routing.path-redirect./=/auth/realms/gamewarden/account
              quarkus.kc-routing.path-redirect./auth=/auth/realms/gamewarden/account
              quarkus.kc-routing.path-redirect./register=/auth/realms/gamewarden/protocol/openid-connect/registrations?client_id=account&response_type=code
              quarkus.kc-routing.path-prefix./oauth/authorize=/auth/realms/gamewarden/protocol/openid-connect/auth
              quarkus.kc-routing.path-filter./api/v4/user=/auth/realms/gamewarden/protocol/openid-connect/userinfo
              quarkus.kc-routing.path-filter./oauth/token=/auth/realms/gamewarden/protocol/openid-connect/token
              quarkus.kc-routing.path-recursive-block./metrics=8443
              quarkus.kc-routing.path-recursive-block./health=8443
              quarkus.http.cors=true
              quarkus.http.cors.methods=OPTIONS,POST,GET,PATCH,PUT,DELETE
              quarkus.http.cors.headers=Content-Disposition,Access-Control-Allow-Headers,Content-Type,Authorization,X-Requested-With
              quarkus.http.cors.access-control-max-age=24H
              quarkus.http.cors.access-control-allow-credentials=true
              quarkus.http.cors.origins=*
      service:
        extraPorts: null
        httpPort: 8080
  metricsServer:
    sourceType: helmRepo
    enabled: auto
    values:
      args:
      - --kubelet-insecure-tls

  minioOperator:
    sourceType: helmRepo
    enabled: true